# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

emInd <- function(X, Y, mu0 = NULL, Alpha0 = NULL, sigb0 = NULL, sige0 = NULL, maxit = 10^3L, epsStopLogLik = 10^-5) {
    .Call(`_vimco_emInd`, X, Y, mu0, Alpha0, sigb0, sige0, maxit, epsStopLogLik)
}

emMultiple <- function(X, Y, mu0 = NULL, sigb0 = NULL, Theta0 = NULL, Lambda0 = NULL, Alpha0 = NULL, fixlambda = TRUE, maxit = 10^3L, epsStopLogLik = 10^-5) {
    .Call(`_vimco_emMultiple`, X, Y, mu0, sigb0, Theta0, Lambda0, Alpha0, fixlambda, maxit, epsStopLogLik)
}

readPlink <- function(stringname, nPheno) {
    .Call(`_vimco_readPlink`, stringname, nPheno)
}

vimco <- function(stringname, nPheno, fit = TRUE, IndAsInit = TRUE, mu0 = NULL, sigb0 = NULL, Theta0 = NULL, Lambda0 = NULL, Alpha0 = NULL, fixlambda = TRUE, maxit = 10^3L, epsStopLogLik = 10^-5) {
    .Call(`_vimco_vimco`, stringname, nPheno, fit, IndAsInit, mu0, sigb0, Theta0, Lambda0, Alpha0, fixlambda, maxit, epsStopLogLik)
}

